### ISSUE TITLE
"Cover" page for HSA

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#112]
If we can give HSA better information upfront, this may smooth out the internal business process and result in more approved applications. It could also be a cool opportunity to delight HSA staff with some friendly copy or baller logo.

Bringing this back from the dead with more clarity on the goal: The cover page would come before the first page of the application and provide curated info/instructions for HSA staff. The goal is to improve/standardize internal business process for Clean cases in order to increase the approval rate.

- [x] @alanjosephwilliams designs it
- [x] @lippytak reviews for content
- [x] @daguar battles with PDFs (slaps it onto the front of every application)

**Comment by lippytak** [comment]
Just spoke w James and Liliana on the phone about a Clean case that was put into the wrong calling queue, which would have resulted in an abandoned/denied case if Liliana had not explicitly followed up about the case. This happened because the RM person who cleared the case didn't have full info on what to do with Clean cases. Consider this a bit more evidence for value of cover page, though for now I'll try to address this with an email to the folks in RM.

**Comment by daguar** [comment]
@lippytak — could you expand a bit on what you mean by "wrong calling queue"?

(Aside, I think it's _fantastic_ process to [1] manually concierge when our system fails to ensure no USER failure while [2] letting the [discovered by real life] failures drive feature dev.)

**Comment by lippytak** [comment]
Sure - basically EWs get their tasks by pulling from various task queues.
One Clean case ended up in a "outreach queue", which is used only
occasionally for real time events like CalFresh in a day and
Project Homeless Connect...so the case stalled. The case should have ended
up in the "cold call queue" which is the basic queue for cases that come in
through MBCW and a few other sources.

**Comment by lippytak** [comment]
More evidence:
![screen shot 2015-01-30 at 5 59 29 pm](https://cloud.githubusercontent.com/assets/2533112/5986377/1d55108a-a8aa-11e4-846b-f5d5449351d6.png)

We're going to talk to a few of the EWs who were confused to figure out why (cf-285? limited info? what info did they need? why did they need it?) and then we can figure out the best way to address it (cover page, individual FU by Carissa, email to staff?)

**Comment by daguar** [comment]
This feature is particularly important if we're expanding to counties with a very light touch relationship — it may even be worth noting that this is _by law_ a sufficient application for processing.

**Comment by lippytak** [comment]
@alanjosephwilliams and I spoke to Carissa and she ran into another case where the EW was confused by 'only 3 pages' and sent out a new application to the client (though continued to process the case as usual). I think it's time for a VERY brief cover page:
- Mark and/or something to make people smile
- Brief description of what this is (legally valid application...)
- Where to go with questions.

**Comment by alanjosephwilliams** [comment]
:thumbsup:

On Mon, Feb 16, 2015 at 4:06 PM, Jake Solomon <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> and I spoke
> to Carissa and she ran into another case where the EW was confused by 'only
> 3 pages' and sent out a new application to the client (though continued to
> process the case as usual). I think it's time for a VERY brief cover page:
>
>    - Mark and/or something to make people smile
>    - Brief description of what this is (legally valid application...)
>    - Where to go with questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/112#issuecomment-74594255>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Yeah, I think we're feeling the pain. Let's do this.

**Comment by alanjosephwilliams** [comment]
Cover letter for review. This version assumes *no data* will be written to the PDF.

![cover_letter_v3](https://cloud.githubusercontent.com/assets/2983464/6307770/85049832-b8f3-11e4-8d26-37e1c0e8501f.jpg)

**Comment by lippytak** [comment]
Awesome. It made me smile! Small things:
- Remove Carissa's contact info and put mine instead (per her request)
- Specify next step is phone interview in the 'handle as usual section' - "Please treat this application like any other CalFresh application. The next step is to get in touch with the client for a phone interview."

**Comment by alanjosephwilliams** [comment]
:+1:

**Comment by alanjosephwilliams** [comment]
![cover_letter_v3](https://cloud.githubusercontent.com/assets/2983464/6308299/2bd5ab20-b8f8-11e4-99e7-276db29c5e7d.jpg)

**Comment by alanjosephwilliams** [comment]
The .indd / jpeg / pdf files are saved in the DB under Health > Clean > Cover Page. I'm reassigning to Dave now that we are ready to package it with applications.
