### ISSUE TITLE
Script the Vagrant VM setup

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#118]
Script the Vagrant setup scripts using shell provisioning: https://docs.vagrantup.com/v2/provisioning/shell.html

Low-priority, but would be useful in future if others need to get set up

**Comment by alanjosephwilliams** [comment]
We are no longer using Vagrant, correct?

**Comment by lippytak** [comment]
Confirmed! Shut it downnnnnn!

**Comment by daguar** [comment]
:+1:
