### ISSUE TITLE
Compile custom pdftk binary with version 2.1

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#120]
I've been messing around with this because for some reason `pdftk` 1.4 (the version used on Heroku and our Vagrant VMs via Apt) appears to be significantly slower than version 2.x (running locally on my Mac).

I compiled a custom binary on a Digital Ocean box, but it appears that it used a different version of `libc` than Heroku uses (2.14 on DO, 2.11 on Heroku) and so it blows up.

![screen shot 2014-08-10 at 12 13 14 pm](https://cloud.githubusercontent.com/assets/994938/3870213/694eeabc-20c2-11e4-8689-fd7e4abc29da.png)

In terms of compiling on Heroku raw, the issue is that pdftk needs `gcj` to be built, and it's not installed by default. One way to address this would be to build `gcj` and then compile from source.

So I see two approaches:

1. Try and approximate a Heroku-dependency-versioned environment for builds on a standalone Ubuntu machine (Digital Ocean) and build there

2. Install necessary additional build dependencies on a Heroku app machine and compile there

I think I'm going to try (2) the next time I take a swing at this.

Links:
- PDFTK build instructions (see "Build PDFTK Server" section at bottom): http://www.pdflabs.com/tools/pdftk-server/
- Heroku Ruby PDFTK buildpack we're currently using: https://github.com/millie/heroku-buildpack-ruby-pdftk (Note: we should still be able to use this buildpack, and just replace the binary that is used there and which lives at https://github.com/millie/pdftk-source , pulled from our own S3 bucket)

cc @migurski in case you have thoughts. I've been using your previous work (eg, https://github.com/openoakland/opendisclosure/issues/24#issuecomment-36692449 and the Python Geo buildpack ) on this as a model, but haven't cracked the nut yet.

This is lower priority, but I wanted to document it here.

**Comment by daguar** [comment]
I don't think we'll need this, as the better solution is a background job and we should do that instead — closing.

**Comment by szTheory** [comment]
@daguar I came across this while searching for how to compile pdftk for cedar. If you are still looking to upgrade, I ended up finding the proper bin/lib for pdftk 2.02 from Ubuntu .deb packages and brought them together here https://github.com/szTheory/pdftk-2.02-heroku-cedar-compiled
