### ISSUE TITLE
caw-pee

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#145]
- General
  - [x] Consider avoiding HSA as acronym throughout
  - [x] 'We' != 'HSA' - Like balance, I think we should keep Clean 'A service from Code for America'. This is more honest and helps us avoid legal issues.
- Personal info
  - [x] Consider telling people why we need this info
- Medi-Cal
  - [ ] Button copy is: 'Next Step: Your Interview'. Consider changing to 'Next Step: Confirm & Submit' (or at least consistent with copy on next page)
- Confirm & Submit: 
  - [x] Let's link out to R&R https://github.com/codeforamerica/calfresh-and-so-clean/issues/122 (Confirm & Submit)
  - [x] 'Please click this box' (and the validation copy) doesn't create value for the client or the assister. If we DO want the client to confirm their intent to submit, then let's highlight that in the copy - "Check this box to confirm your intent to submit your CalFresh application" or something.
  - [x] Let's try to think of a way to communicate to people here that you'll still have a chance to upload verification docs. Most (all?) assisters will know that verification docs are required, and I think people will hesitate to click submit: "Wait...I'm not done yet, did I miss the document upload part?? Let me go back and see..."
- Confirmation
  - [x] 'cook and prepare' > 'buy and cook'
  - [x] Consider removing the 'what's next from us' section to help people focus on the doc upload before getting distracted with a future phone call. What do you think about saving it for the completion page?
- Upload 
  - [ ] Header copy obscures the document type, which usually wraps to the next line. Consider ways to highlight the doc type while also keeping it action oriented.
  - [x] Change 'submit' copy on button to 'upload' or something that doesn't make feel like they're submitting another app?
- Complete
  - [x] 'Eligibility interview' is a bit jargony and isn't used anywhere else in the app
  - [x] Remove All done! button if it doesn't do anything (maybe go back to root?)

**Comment by alanjosephwilliams** [comment]
^^ see immediately previous comment from October. Let's start fresh on copy updates.
