### ISSUE TITLE
Use phone/email input types on form fields for better mobile experience

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#187]
Using HTML 5 input types could greatly improve the experience on mobile:
- type=number for SSN
- type=date for DOB
- type=tel for phone
- type=email for email

I think these will all bring up custom keyboards on iOS and Android. More info: http://www.w3schools.com/html/html5_form_input_types.asp. If this was intentional and for IE support or something then OOPS + feel free to close.

**Comment by alanjosephwilliams** [comment]
d d done
