### ISSUE TITLE
Clean testing and refactoring

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#219]
Starting a list for our cleanup today:
- [x] Sanitize branches (produ == master + dev)
- [x] Delete dead branches
- [x] Reopen issues for outstanding features that never got merged (still contained outstanding feature branches)
- [x] Confirm local setup running smoothly without vagrant for all
- [x] Delete Vagrant stuff
- [x] Add .env* to .gitignore everywhere and always
- [ ] calfresh_web.rb > app.rb
- [ ] Move encrypted cookie setup to test configuration
- [x] Get versioning info out of views/filenames
- [x] Update readme (include .env example in readme)

**Comment by lippytak** [comment]
deprecated issue @daguar?

**Comment by lippytak** [comment]
Title change from: Clean up Clean

**Comment by lippytak** [comment]
@daguar see #310 and #311 for the specific testing goals this sprint. Feel free to close this one if you think they cover it.

**Comment by daguar** [comment]
Keeping this in "Ready" because I think it has broader scope, and I may dive into that scope (deep test coverage + deep refactor) next week while traveling.

**Comment by daguar** [comment]
This can largely be considered done for now, since this is old (pre-Rails) and it's worth opening new and smaller issues for this (PR finishing first pass at full testing will close this.)
