### ISSUE TITLE
Change subheader to remove emphasis on Medi-Cal

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#228]
Right now the repo header says:

> Minimalist online application for CalFresh and Medi-Cal

I'd like to remove "and Medi-Cal".

This is a minor change, but the reason is that — while, yes, we give people the option of also getting Medi-Cal, they _must already eligible for CalFresh_. Given that the universe of folks eligible for Medi-Cal is larger, I'd personally like to de-emphasize it for anyone who stumbles upon the project.

**Comment by alanjosephwilliams** [comment]
Will be addressed by #340

**Comment by daguar** [comment]
I originally opened this issue just to ask about the header for the _GitHub repository_ specifically — it seems like there's consensus to downplay Medi-Cal more generally (maybe even remove it) so I'm just unilaterally removing it from the GitHub repo header.

(This is heavy process for this but I'm just leaving a record before I close!)
