### ISSUE TITLE
Rename repo from "Calfresh and So Clean" to just "Clean"

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#234]
That seems – erm, no pun — cleaner. What say you? @lippytak @alanjosephwilliams

**Comment by daguar** [comment]
(PS of course the rename creates a redirect so we're all good with old links)

**Comment by alanjosephwilliams** [comment]
Sadly its time

On Fri, Jan 9, 2015 at 3:26 PM, Dave Guarino <notifications@github.com>
wrote:

> (PS of course the rename creates a redirect so we're all good with old
> links)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/calfresh-and-so-clean/issues/234#issuecomment-69418759>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
