### ISSUE TITLE
Clean outreach

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#236]
I'm going to spend a big chunk of February getting Clean users (assisters) and then supporting them. I'm going to keep this simple and start with high touch convos and ask everyone to intro me to other CBOs that serve may serve our target pop. The goal is to have every CBO in SF know they can use Clean to help their clients apply for CalFresh in 10 minutes or less and SUPPORT the hell out of those who choose to try it. Hopefully over time we can empower (and incentivize) users to share Clean with others. When it comes to support I'll lean heavily on Liliana (the Community Ambassador) for program expertise and Carissa (the County Ambassador) to make sure clients are having a good experience with HSA.

Got overwhelming already, moving to GDocs: https://docs.google.com/a/codeforamerica.org/spreadsheets/d/13ctYxwtTguhQVH4TxlOi_E6vyyWJ-aL9y-OriKBhhLw/edit#gid=0

Running list of nonprofits and some notes on how they're structured:
- **Family Resource Centers:** Essentially, every neighborhood in SF deemed high needs has a CBO known as a Family Resource Center (FRC). FRC's receive many referrals funneled to their agency via HSA, SFUSD, General Hospital, and DPH. These agencies usually have a plethora of case managers and family advocates or directors ;) who assist with applying to most benefits.
- **Office of Financial Empowerment**: Maybe good connector to all the free tax prep resources

**Comment by daguar** [comment]
Moving this to 'current sprint' because it's similar to what we have down as "concretize next steps to grow/fuel outreach" on Clean.

@lippytak feel free to break this down/rename/create new issue.

**Comment by lippytak** [comment]
:+1: renamed the issue to be more specific

**Comment by lippytak** [comment]
@daguar I want your quick thoughts/feedback this afternoon and then I'm going to get rolling. The bottom  line is we just need more users to know what they need and more applicants to map and improve the funnel.

**Comment by daguar** [comment]
All sounds good to me.

**Comment by alanjosephwilliams** [comment]
Seems like the key assets to support this (none necessarily required to get started with outreach) are:
- easily verified social proof
- clear instructions
- a known place to ask questions (and good management of the ensuing community)
- a feedback loop that encourages their continued use and sharing it with others.

**Comment by lippytak** [comment]
FIrst wave of emails sent

**Comment by lippytak** [comment]
More doing less planning (changing the title)! I'll be noting progress/full contact list here until it gets too long to handle in a single GH issue.

**Comment by lippytak** [comment]
From now on I'm going to start doing mini surveys with CBOs as I talk to . I'll document everything here: https://github.com/codeforamerica/health/wiki/CBO-research

**Comment by lippytak** [comment]
Great meeting with South of Market Family Resource Center on Fri. 

BLUF: SOMACC sees ~2k very low income clients in SOMA per year, helps ~100 families apply for services but has a pretty bad experience overall. Daisy is a true advocate and goes with clients to their HSA appointments. She laments, "I don't get how eligible people keep getting turned away." IMO SOMACC is a great opp for Clean...

Details: https://github.com/codeforamerica/health/wiki/CBO-research#south-of-market-family-resource-center-somacc

**Comment by lippytak** [comment]
Community West Works (CWW) BLUF: I met with an intensive case manager at CWW named Chloe. She has an awesome 'do whatever it takes' attitude and has done her own personal CitizenOnboards just to understand how things work for her clients - she applied for an emergency shelter bed via 311 a couple months ago and learned it takes 30 days to get a call back. Eep. Unclear if her clients are the right target population but I think the drug felon legislation may change that.

Every Day Connect (EDC) BLUF:offers a targeted set of daily services for mostly homeless clients. Unclear how many clients would be interested/eligible for CalFresh because they've never advertised it, but Emily wanted to start a CalFresh app pilot right away to learn. I'm going back for a staff training on 2/25 to kick it off.

Details: https://github.com/codeforamerica/health/wiki/CBO-research

**Comment by lippytak** [comment]
Today:
- Scheduled meeting with USDA to discuss summer meals prog
- Emailed  Rec and Park
- Setup meeting with SF Office of Financial Empowerment (network group)
- Looking for intro to the other big tenderloin housing group (forget name, not THC)
- Looking for intro to SF Human Services Network
- Emailed ConnectingPoint
- Scheduled appt to present at next food security task force mtg early March

**Comment by lippytak** [comment]
Closing this one for now. See notes so far: https://github.com/codeforamerica/health/wiki/CBO-research
