### ISSUE TITLE
Implement technical changes to expand to another county

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#238]
Spec'd out in #237 

- Create new Heroku app(s) — fork with some env var changes, such as email address to send to
 - In new instance, set env var password for zip files
- Miscellaneous text references throughout
 - Root page: county name (replace SF with env var ref)
 - Review/submit page: County phone # 
 - Interview page & Addl household member pages: remove reference to the name of the agency and make generic
 - Complete page: remove county-specific stuff, maybe have to env var some stuff if we want it there
- URL in email — turn into env var and set on all instances
- Domain name: https://COUNTYNAME.cleanassist.org would be nice

**Comment by lippytak** [comment]
Looking like we might not be able to get staff time for case tracking early on. One alternative would be to incorporate a release of information into the application so we can call to check case status on the client's behalf.
