### ISSUE TITLE
Force SSL

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#246]
https://clean-production.herokuapp.com/ works as expected and shows a good cert.

http://clean-production.herokuapp.com/ also works...but doesn't seem to be forcing SSL?
![screen shot 2015-01-25 at 1 35 34 pm](https://cloud.githubusercontent.com/assets/2533112/5893399/10c6ae6c-a497-11e4-9fda-8414e1fbf650.png)

Maybe this is a bug? https://github.com/codeforamerica/clean/blob/master/calfresh_web.rb#L17

**Comment by daguar** [comment]
Yeah I looked at this a bit last week and think it's not fully forcing.

**Comment by lippytak** [comment]
@daguar :+1: k cool - updating the issue to reflect the next step (figure out the fix).

**Comment by lippytak** [comment]
@daguar Putting on a +1 on this because I'm just now starting to share links to https://www.cleanassist.org more publicly and no doubt people won't remember to keep that 's' intact!
