### ISSUE TITLE
Switch to Rails

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#252]
- [x] Initialize new Rails app
- [x] Migrate all gems over
- [x] Merge @lippytak's UI changes PR into dev, rebase against dev
- [x] Get tests running + failing
- [x] Get the tests passing in Sinatra passing in Rails
- [x] Migrate CSS JS and cross-check visuals and functionality against Sinatra app
- [x] Get PDF assets needed for writing in correct place
- [x] Confirm Rails version working on Heroku
- [x] Do line-by-line review of Sinatra code for any untested/ops stuff (eg, forcing SSL, encrypted cookie) and list out those things
 - [x] Force SSL in production
 - [x] STDOUT goes to Heroku logs
 - [x] Encrypt cookie/session
 - [x] Make sure all Redis instantiations use ENV instead of `settings`
 - [x] Clear session at root + beginning of application
 - [x] Check verification_doc_layout and see if it's necessary to migrate
 - [x] Log session data before each controller action (or decide explicitly to no longer do that)
 - [x] Migrate over CalFresh application images folder to `lib/calfresh/` and modify Calfresh library to read from a relative folder path
 - [x] Add SecureRandom gem (oh yeah! not a gem; in std lib)
- [x] Review all tests and make pending if need work
- [x] Set up SECRET_TOKEN trick
- [x] Update README
 - [x] Add details on Postgres
- [x] Test manually on dev (do full application process w/ verification docs, and check all zip files emailed for goodness)
- [ ] Deploy

**Comment by lippytak** [comment]
HEADER CHANGED

**Comment by lippytak** [comment]
Coffee is for closers. Would be awesome to ship this by EOW. Everything else is a distraction. Prizes await!

**Comment by daguar** [comment]
See above checklist for pieces of this (will be updated); work is being done on the migrate-to-rails branch https://github.com/codeforamerica/clean/tree/migrate-to-rails

**Comment by daguar** [comment]
Gems migrated

**Comment by alanjosephwilliams** [comment]
this is riveting to watch

**Comment by daguar** [comment]
Added:

- [ ] Merge @lippytak's UI changes PR into dev, rebase against dev

**Comment by daguar** [comment]
Blowing away current migration branch and starting anew — having conflicts and odd errors from initializing in the same folder, so going to start again with a more "1. build Rails setup, 2. migrate code over" approach.

**Comment by daguar** [comment]
Rebased to include the bug fix for #259 contained in #263.

**Comment by daguar** [comment]
Added:
- [ ] Migrate CSS JS and cross-check visuals and functionality against Sinatra app

**Comment by daguar** [comment]
All tests that were passing in Sinatra now pass in Rails.

**Comment by daguar** [comment]
Added:
- [ ] Get PDF assets needed for writing in correct place

**Comment by daguar** [comment]
Have migrated JS, CSS and confirmed that most (save for doc upload, which I need to shave back end yaks on first) are working.

**Comment by daguar** [comment]
PDF assets all good; some system PDF issues locally right now, but appears to be an OSX artifact.

**Comment by daguar** [comment]
Added:
- [ ] Confirm Rails version working on Heroku

AND CHECKED IT OFF, YO.

**Comment by daguar** [comment]
Done with forcing SSL in production

**Comment by daguar** [comment]
Added a bunch of shit to do after line-by-line code review

**Comment by daguar** [comment]
We get session encryption for free with Rails! ;D

**Comment by daguar** [comment]
Secret token setup done

**Comment by daguar** [comment]
Confirmed Redis only uses ENV URL

**Comment by daguar** [comment]
Confirmed with @alanjosephwilliams on Slack that `verification_doc_layout` does not need to be migrated

**Comment by daguar** [comment]
Added code and tests to clear session at root and first application page (for new application)

**Comment by daguar** [comment]
Done with: Log session data before each controller action

May want to not do that in the future

**Comment by daguar** [comment]
Finished:
- Migrate over CalFresh application images folder to lib/calfresh/ and modify Calfresh library to read from a relative folder path

but also that code is no longer used, so whatevs

**Comment by daguar** [comment]
Have reviewed all tests, made the ones pass that needed some love, and marked as pending the ones that need some work.

**Comment by daguar** [comment]
Updated README with Rails details

**Comment by daguar** [comment]
WOOT! Have tested on dev, and confirmed it all works end-to-end!!

Waiting to deploy until tomorrow.

**Comment by daguar** [comment]
Live in dev, demo, and production.
