### ISSUE TITLE
Obtain Railsification prizes for Friday

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#254]

**Comment by daguar** [comment]
related to #252

**Comment by daguar** [comment]
Added initial checklist with subtasks to the main issue, specifically:

- [ ] Initialize new Rails app
- [ ] Migrate all gems over
- [ ] Get tests running + failing
- [ ] Get tests passing
- [ ] Do line-by-line review of Sinatra code for any untested/ops stuff (eg, forcing SSL) and list out those things
- [ ] Deploy

**Comment by daguar** [comment]
Added:

- [ ] Set up SECRET_TOKEN trick
- [ ] Update README

**Comment by daguar** [comment]
Added:

- [ ] Test manually on dev

**Comment by daguar** [comment]
Oh shit totally putting this stuff on the wrong issue — migrating content over to #252 .

**Comment by lippytak** [comment]
It shall be late. But it shall be.
