### ISSUE TITLE
Turn on SF CalFresh ads and start assisting real people

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#256]
Like this (but we call instead of the food bank): https://github.com/codeforamerica/clean/issues/207

**Comment by lippytak** [comment]
Got a few ads up for $25/day:
![screen shot 2015-02-14 at 5 33 31 pm](https://cloud.githubusercontent.com/assets/2533112/6201739/c02fbc1c-b46f-11e4-9e36-eb148087afc8.png)

Pointing to this survey: https://codeforamerica.wufoo.com/forms/get-help-applying-for-calfresh-in-san-francisco/

Completed surveys will send SMS alerts to me and email alerts to health-lab@

**Comment by alanjosephwilliams** [comment]
awesome.

On Sat, Feb 14, 2015 at 5:35 PM, Jake Solomon <notifications@github.com>
wrote:

> Closed #256 <https://github.com/codeforamerica/clean/issues/256>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/256#event-235918502>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
