### ISSUE TITLE
Create TeamClean@ alias

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#258]
I want to make TeamClean alias, add EVERYONE working on Clean (CfA, food bank, HSA), and CC this alias for basically all internal/external Clean communications. Ideally this would create full transparency around bottlenecks AND create collective ownership around solving them. Right now I'm the only one with (mostly) full view.

This would be a lot of messy emails going to a lot of people, include some higher ups, so I'm not sure if this is the right approach and want to discuss with @RebeccaCoelius first.

**Comment by daguar** [comment]
This is done, yes? If so, could feel free to close!
