### ISSUE TITLE
Set up helpful error web page w/ backup instructions

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#261]
Replace 500/404 default error pages with a nice one that tells users what to do if Clean has somehow broken. Liliana from the Food Bank has given nice instructions on what to do so we can lean on those.

**Comment by alanjosephwilliams** [comment]
I'll drop mocks or views here then reassign to for implementation (or you can reassign for implementation now and I'll take the baton when its time to get the content and design up to par).
