### ISSUE TITLE
Sketch and build better "additional household member" flow

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#277]
It's time to improve the UX of documenting additional household members. Currently, you must add them one at at time, and after you add each, you are routed back to the same view on which you were originally prompted. The language is kludgy and the experience is bad. 

Let's either:
- ask for the number of household members up front and structure the experience accordingly, or
- at the very least, include a second view with more appropriate language for every member after the first.

**Comment by lippytak** [comment]
Maybe a separate issue but I think we could improve the UX with only copy changes, too: https://github.com/codeforamerica/health/wiki/CBO-research#community-works-west-cww--womens-reentry-program

**Comment by daguar** [comment]
@alanjosephwilliams — Looks like you implemented the second option described in this issue in your copy audit PR ( #358 ).

So I'm going to close this with the presumption that this is good enough for now to address this issue; please reopen if you think we should do more on this in the near future.

**Comment by alanjosephwilliams** [comment]
I think this should remain closed for now. Further improvements should be
articulated as a unique issue.

On Mon, Feb 23, 2015 at 1:30 PM, Dave Guarino <notifications@github.com>
wrote:

> Assigned #277 <https://github.com/codeforamerica/clean/issues/277> to
> @alanjosephwilliams <https://github.com/alanjosephwilliams>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/277#event-240477834>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
