### ISSUE TITLE
Research: who is eligible, interested, and not enrolled?

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#28]
We need to dig into who the population is that is:

- Eligible
- Interested (eg, not asset-rich and so not feeling like they need CalFresh)
- Not enrolled

Some quick policy paper research into this would be great.

Some questions of note to me are:

- What's this population look like at a basic demographic level?

- Who are the **uninterested** folks?

- What's the "real potentially eligible" number look like (ie, excluding those uninterested or otherwise not really the target of CalFresh)

- What potential enrollees represent the "low-hanging fruit" for our work?
(ex., people who Google "SF food stamps", start the app online, get discouraged and don't come back -- perfect opp for us to have an impact)

- What does the CA county variation look like, and where might our work play an opportunity?

A useful excerpt to start, from PPIC:
> [T]he USDA estimates that slightly more than half of eligible Californians participate in CalFresh—this is one of the lowest statewide participation rates in the nation. Participation also varies across California’s counties. This begs the question of how much lower poverty rates would be—would they still be the highest in the country?—if participation rates were higher. As this example shows, housing costs are not the only area in which California stands out. And, while policy clearly plays an important role in offsetting the higher cost of living in California (it more than offsets cost of living in families with children), it has the potential to move the needle on poverty even further.
http://www.ppic.org/main/blog_detail.asp?i=1467

**Comment by alanjosephwilliams** [comment]
I just migrated these links and some of Dave's commentary to the Health Wiki. 

https://github.com/codeforamerica/health/wiki/Research:-Who-is-Eligible,-Interested,-and-Not-Enrolled-in-CalFresh%3F
