### ISSUE TITLE
Clean homepage content

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#282]
Targeted at CBOs

**Comment by daguar** [comment]
So this'll be something like cleanassist.org/about ?

**Comment by lippytak** [comment]
I'm thinking changes to cleanassist.org + maybe an /about page

**Comment by lippytak** [comment]
Important things to hit:
- what this website does (apply for CalFresh in SF in <10 mins)
- other steps in the process (2 = interview, 3 = docs)
- BLUF on what CF is (~$200/month for healthy groceries)
- don't stay food stamps because it's stigmatized

Mockups:
![2015-02-04 15 43 46](https://cloud.githubusercontent.com/assets/2533112/6052277/b0ed1278-ac85-11e4-804d-84ca3b3ba0fd.jpg) 
![2015-02-04 15 43 40](https://cloud.githubusercontent.com/assets/2533112/6052278/b0ef96b0-ac85-11e4-9ccf-e3c485703ba9.jpg)

Reassigning to @ajw to implement as it's more than what a measly PM can handle (copy changes).

**Comment by lippytak** [comment]
Worth a quick look at the big "landing page as a service" companies that have put a ridiculous amount of thought into landing page layouts. Maybe we can jack some basic styles vs. starting with raw bootstrap (e.g. http://signup.havenconnect.com/ > http://launchrock.co/)

**Comment by alanjosephwilliams** [comment]
Let's save changes to styles for a more thoughtful refresh. Lots of frontend work to do in our next one or two sprints. #295 will close this issue.
![image](https://cloud.githubusercontent.com/assets/2983464/6087052/a9c6c8e6-adfb-11e4-9ac5-17b8dd20f0a7.png)

**Comment by daguar** [comment]
Closed with the merge of #295. Thanks!

**Comment by lippytak** [comment]
A couple nitpicks on homepage for @alanjosephwilliams. LMK if you want me to open another issue this is mostly an FYI to consider during continued frontend work.

- Let's either define or not use 'HSA' acronym
- The benefit amount is up to $200 *per person*
- Let's not use "prove your need" because lots of people who qualify don't think they "need" it. Food Bank really strongly avoids 'need' language. CalFresh is about making families/communities healthier.

**Comment by alanjosephwilliams** [comment]
yes let's iterate rapidly ;)

On Fri, Feb 6, 2015 at 4:31 PM, Jake Solomon <notifications@github.com>
wrote:

> A couple nitpicks on homepage for @alanjosephwilliams
> <https://github.com/alanjosephwilliams>. LMK if you want me to open
> another issue this is mostly an FYI to consider during continued frontend
> work.
>
>    - Let's either define or not use 'HSA' acronym
>    - The benefit amount is up to $200 *per person*
>    - Let's not use "prove your need" because lots of people who qualify
>    don't think they "need" it. Food Bank really strongly avoids 'need'
>    language. CalFresh is about making families/communities healthier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/282#issuecomment-73339068>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
