### ISSUE TITLE
Usability research on household feature/flow

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#284]

**Comment by alanjosephwilliams** [comment]
This consists of something like:
- [ ] talking to the assister that helped with each applicant
- [ ] observing some assisters closely during this part of the process
- [ ] auditing the copy

other suggestions?

On Mon, Feb 2, 2015 at 11:37 AM, Jake Solomon <notifications@github.com>
wrote:

> Assigned #284 <https://github.com/codeforamerica/clean/issues/284> to
> @alanjosephwilliams <https://github.com/alanjosephwilliams>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/284#event-228757128>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
I also think you could also learn a lot by talking to CfAers who have a bit of knowledge about various gov programs/social services but not specifically CalFresh. Maybe roughly comparable perspective to CBOs who don't currently do applistance assistance (but should).

**Comment by alanjosephwilliams** [comment]
We did some observation this week of Francesca assisting folks at HPP. We didn't get a big sample of people to observe, but F blew right threw this portion of the application. For a regular user, this does not seem to present friction. We should keep an eye toward this as we conduct a full [copywriting audit](https://github.com/codeforamerica/clean/issues/298)

**Comment by alanjosephwilliams** [comment]
Closing for now.
