### ISSUE TITLE
Run performance benchmark (time) on filling out full 10-page application PDF

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#289]
This is if there is evidence that this creates weirdness inside HSA when they receive the app (they currently only get 3 pages.)

@lippytak — chime in here if it turns out this would be useful to benchmark.

**Comment by lippytak** [comment]
:+1: thx sorry meant to open this earlier

**Comment by daguar** [comment]
On clean-dev (a single 2x [double size] dyno), here is the comparison with only one try each:

- 3-page PDF (current): 7.2 seconds
- 10-page PDF: 9.2 seconds

**Comment by daguar** [comment]
With a second benchmark on dev, it's just under 9 seconds, so it's fairly consistent.

More details on the benchmark:
- 1 additional household member
- Two-digit years in birth dates
