### ISSUE TITLE
Growth hacking (what good folks call "outreach"): the thread

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#29]
How we connect to our target users is a key question here. This thread is to throw ideas at the wall that we can test.

- **Inreach**

"Inreach" is connecting with people already enrolled in (or eligible for?) other programs as a means to identify people likely eligible for CalFresh. [Nutrition for Los Angeles Families (NFLAF) called this out](http://cfpa.net/CalFresh/NFLAFProject/NFLAF-CoalitionSignOnRequest-2013.pdf) in its 2013 push to up enrollment.

Crazy idea -- buy Adwords not just for "CalFresh" or "food stamps", but also things like "Medi-Cal" and "free health care sf" or anything else that we think folks _who would be eligible_ might be looking for. The ad could be something like "sign up to get free money to buy food from the City of San Francisco in 3 minutes".

Another way to use inreach -- identify other "intermediary" users who are providing services to our perceived population, but for whom CalFresh isn't the focus. They might be super keen on helping people enroll if it takes 5 minutes instead of 60, and is straightforward to do.

**Comment by alanjosephwilliams** [comment]
This thread is old and not specific enough to keep open. Shuttin' it down.
