### ISSUE TITLE
Possible Clean application didn't go through

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#290]
Saw this sendgrid notice in my inbox:
![screen shot 2015-02-04 at 4 17 14 pm](https://cloud.githubusercontent.com/assets/2533112/6052586/6428cc58-ac89-11e4-812f-4712d4db7fe9.png)

Came around the time @alanjosephwilliams was at HPP.

I'll investigate and report back here in the next hour or so.

**Comment by lippytak** [comment]
I think we're all good. Emotional downgrade from EBF to regular bug. I'm going to try to confirm with send grid support and will follow up here/close issue I know what's happening.

**Comment by daguar** [comment]
Looked at logs — API response from Sendgrid was "success".

**Comment by lippytak** [comment]
BLUF: All good, closing issue.

Details:
- Reputation is good so wouldn't expect filtering issues
![reputation is good](https://cloud.githubusercontent.com/assets/2533112/6053430/082ecf46-ac94-11e4-9f7d-98f6bf857f00.png)

- All emails today showed delivered
![7 emails delivered today](https://cloud.githubusercontent.com/assets/2533112/6053432/0eb59b6a-ac94-11e4-8f44-1e46ecf86597.png)

- But we have 9 deliveries with 7 requests...just a bit confusing
![requests-delivered](https://cloud.githubusercontent.com/assets/2533112/6053433/15cf2556-ac94-11e4-8799-92794badf782.png)

And a chat with support:
![screen shot 2015-02-04 at 5 32 36 pm](https://cloud.githubusercontent.com/assets/2533112/6053439/243dd646-ac94-11e4-9e58-7b7828aa8ff1.png)

![screen shot 2015-02-04 at 5 32 49 pm](https://cloud.githubusercontent.com/assets/2533112/6053440/2acef3aa-ac94-11e4-9f99-02d088d9cb01.png)

![screen shot 2015-02-04 at 5 32 56 pm](https://cloud.githubusercontent.com/assets/2533112/6053442/2d1e5844-ac94-11e4-8d7f-98da1f1f5bfc.png)

![screen shot 2015-02-04 at 5 35 53 pm](https://cloud.githubusercontent.com/assets/2533112/6053451/491201ae-ac94-11e4-911e-03a0c4d85a6b.png)
