### ISSUE TITLE
Clean Crash

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#293]
Just got another 'send grid delivery rate drop' alert. I'll look into it now to triage and let folks know if we need to fix it tnight. I'll report back here shortly!

**Comment by lippytak** [comment]
![relevant](https://cloud.githubusercontent.com/assets/2533112/6072773/580b2156-ad5a-11e4-90f4-c9a9cc2ea75c.png)

Will talk to user soon and report back!

**Comment by lippytak** [comment]
Using windows RT for a case of 2 people with ~7 verification docs.

Not an EBF as it's not stopping a user in the moment but @daguar I think it would be great if you could prioritize investigating the logs tomorrow and then decide whether you think it's best to address in the sinatra app or wait for rails first. That work?

**Comment by lippytak** [comment]
@lippytak will try to get in touch with Xiao to get plausible time limit on the case. IF she thinks it was plausible that it took ~30 mins between first and last doc upload, then we'll consider this known and fixed. Otherwise we'll have to keep digging...

**Comment by lippytak** [comment]
@dave I see you have a post-mortem issue on the board. Let me talk with Xiao first and then I'll reassign to you once we have more info.

**Comment by daguar** [comment]
:+1: 

To document this a bit more, the potential causes were:

- Timeout of Redis expiration (which we fixed in #299 )
- Something wrong with document upload (which we'll get at with #311)

**Comment by lippytak** [comment]
Waiting for call from Xiao

**Comment by lippytak** [comment]
Spoke to Xiao yesterday. Technical stuff:
- 'Internal server error' when she clicked 'Submit my docs'
- iPhone 4s
- 7 docs = 7 photos (so pretty large)
- No wifi connection
- No way it took ~30 mins (no convo in the middle, just going through 7 in a row)

@daguar Given this, let me know if we still need to reproduce the issue or if we think it's solved. I'm happy to help figuring out repro steps.

Human stuff:
- After the first error Xiao hit the back button and tried again TWICE (aka 21 photos in total...ugh!)
- Office hours were ending and client was really in a rush
- After 2 internal server errors Xiao said she should just go
- Xiao checked the camera roll and the docs weren't saved :(
- Client went back to Women's building a couple days later but Xiao wasn't there (only 1 day/week)
- Then client went to 1235 but was told she couldn't drop off verification docs there (WHAT?!)...
- So now they're trying to meet up again so Xiao can send in verification docs

Ugh :-1: ! So given all crappiness, I decided to deploy our fist installment of the crash to cash program:
![crash-to-cash](https://cloud.githubusercontent.com/assets/2533112/6152690/ff644d60-b1d3-11e4-8e38-52028b22f2b3.jpg)

I dropped it off at the FB this morning. Xiao was really happy about this..."she'll be so happy, she really needs money right now!" So I think for this case this was the right thing to do. In the future we'll better equip users to deal with errors in the moment ('what you can do right now') and get an apology gift to clients immediately instead of days later.
