### ISSUE TITLE
Windows RT: Form placeholder copy removed on focus

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#296]
When the user taps into a form field, the placeholder text is removed—thus removing the messaging about _what they should be entering_. As a result, we are seeing users tap into the next form field to remind them about what to enter, then tapping back to enter it. It's awful.

**Comment by alanjosephwilliams** [comment]
PR #340 will close or deprecate this since we have removed our dependence on placeholder text to give users context about each form field.

**Comment by daguar** [comment]
Closed with merge of PR #340
