### ISSUE TITLE
Give the signature its own view

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#297]
We ask people to sign their Clean Assist application with a swipey little signature box. It's p fun for some people. For most people though, it totally sucks. In part because we make it about 1/5 the size of every other swipey signature experience out there. Pending a deeper policy investigation into whether we can get away with typed signatures, let's give the signature gesture some love—by giving it is own view, and as much real estate as we can muster.

**Comment by lippytak** [comment]
We could also force horizontal layout for this screen.

**Comment by alanjosephwilliams** [comment]
That could be a decent interim improvement. From what I have observed, the
horizontal orientation t makes a noticeable difference in users' comfort
signing with their index finger, while the assister holds the device. Let's
try it it out and see if if the forced layout change is a problem.

On Sat, Feb 14, 2015 at 10:09 AM, Jake Solomon <notifications@github.com>
wrote:

> We could also force horizontal layout for this screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/297#issuecomment-74385527>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Relevant:
- http://stackoverflow.com/questions/8738072/forcing-web-site-to-show-in-landscape-mode-only
- http://stackoverflow.com/questions/4806938/is-there-a-way-to-force-horizontal-landscape-layout-on-mobile-devices/4807047#4807047

**Comment by alanjosephwilliams** [comment]
We are just going to give people a nudge using our established warning style. Implemented in #372.
