### ISSUE TITLE
update brand in the app

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#305]
- [x] Remove "CalFresh & Medical"
- [x] Include Clean / CleanAssist
- [x] Indicate that it is "San Francisco" specific.
- [x] Update typography (ditch Brandon Grotesque, implement Transport (not yet confirmed))

**Comment by alanjosephwilliams** [comment]
This is blocked by #308

**Comment by alanjosephwilliams** [comment]
Will close with #305

**Comment by daguar** [comment]
Closed by PR #340
