### ISSUE TITLE
Get Help Now! (feature)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#306]
Intercom.io only works with logged in users. Here's what Olark feels like:
![screen shot 2015-02-08 at 1 38 46 pm](https://cloud.githubusercontent.com/assets/2533112/6098581/9469a042-af98-11e4-84b2-c1170c751aa2.png)

![2015-02-08 13 39 20](https://cloud.githubusercontent.com/assets/2533112/6098585/a9ce5c3e-af98-11e4-893c-01de69d7ccdb.png)

![2015-02-08 13 39 34](https://cloud.githubusercontent.com/assets/2533112/6098586/abc722be-af98-11e4-8dc0-1b6f8de55d34.png)

Not perfect but net positive IMO. What do you think @alanjosephwilliams? We can discuss in sprint plan.

**Comment by lippytak** [comment]
You can check it out on the Olark branch: https://github.com/codeforamerica/clean/tree/olark

**Comment by alanjosephwilliams** [comment]
not perfect but net positive sounds about right to me.

FWIW, I didn't see any evidence of Olark on that branch. What obvious thing am I missing?

https://www.dropbox.com/s/oak3povjrw2u4b9/Screenshot%202015-02-08%2014.38.41.png?dl=0

**Comment by alanjosephwilliams** [comment]
worth noting that Olark says they support IE 8 and up.

**Comment by lippytak** [comment]
Oops forgot to commit change. Done now!

**Comment by lippytak** [comment]
I'll own this.

**Comment by lippytak** [comment]
Instead of my cell we'll use the 'clean-outreach' number and have it ring all of us: https://www.twilio.com/blog/2009/05/dialing-multiple-numbers-simultaneously-with-twilio.html

**Comment by lippytak** [comment]
Replaced with better help channels in the footer: https://github.com/codeforamerica/clean/issues/518
