### ISSUE TITLE
Interim brand update

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#308]
As we look to create more marketing materials and a product more easily adopted by CBOs, we need to actually put some effort into creating an identity for Clean.

An outstanding job is beyond my skillset—any really, beyond anyone's at CfAs (except Molly). We should consider in the medium term contracting with a graphic design studio to help us build out a brand that will scale.

So, indexing toward high ROI and low "I", I think we need to following, as soon as possible:

- A presentation of 2-3 directions for the stylized name—"Clean" or "Clean Assist". Essentially, this is a single illustrator panel showing some different "treatments"—combinations of typography and layout. This will by no means be exhaustive—we'll limit ourselves to fonts that are either free or available through existing subscriptions like TypeKit. We'll come away with a couple of choices, and I'll make a recommendation.

- Following from that, we need to see some different typography combinations *in the app*. This includes titles, section headers, form labels, and body copy. Essentially, I'll create a new branch, create the salient SCSS variables, and the implement a few combinations and take screenshots to present to the group. We'll come away with a couple of choices, and I'll make a recommendation.

Given work done on this already, this feels like about a day of work. We will by no means feel like the work is optimal or "complete", but we'll have something that addresses the entire surface area of our needs, and that will **unblock** the development of quality marketing assets.

Obviously @mollymcleod should be the critic we aim to please.

**Comment by lippytak** [comment]
@alanjosephwilliams as discussed in sprint plan the sprint goal is:
- create a mark
- typography update in app
- get in an order of Clean wallet cards for clients

**Comment by alanjosephwilliams** [comment]
I'm going to let this one close with the merging of #340. I'll open separate issues for anything left on the table.

**Comment by alanjosephwilliams** [comment]
I'm going to let this one close with the merging of #340. I'll open separate issues for anything left on the table.
