### ISSUE TITLE
Observe one assister or join a CBO meeting

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#312]

**Comment by lippytak** [comment]
@daguar and @alanjosephwilliams I forgot to discuss this card during sprint plan, but I think it's really important this week that we all observe an assister or at least join a CBO outreach meeting. I'll give you a couple options on your calendar. @daguar LMK if you don't have bandwidth (LOTS on the board this week!) and we can talk about what to take off to make this happen.

**Comment by daguar** [comment]
I'm gonna head to MEDA tomorrow if that's alright. I want to know them better specifically, and the timing works well for me.
