### ISSUE TITLE
Research e-signature

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#326]
**Current problems:**
- Doesn't work on Windows RT at all, which is what the Food Bank uses for app assistance
- Doing a signature on a mouse or trackpad is painful and requires pretty fine motor control
- The signature area is too small and should probably have it's own view (see #297)

**Options/next steps from best to worst:**
- Let's ditch a physical signature and use an e-signature instead
  - I will discuss with Deven (CfA lawyer) today
  - I will discuss with CDSS lawyer asap (hopefully next week)
  - Depending on their feedback, I'll get the :+1: from Leo
- If not, let's try to fix the signature area on Windows RT (I'll either buy one or get one from FB to test)
- If not, let's just buy other tablets for the Food Bank + check with Jennifer on getting corporate donations from Google

We'll include this in next week's sprint plan. Good? Good.

**Comment by lippytak** [comment]
MBCW, C4 and LEADER for context:
![mbcw-signature](https://cloud.githubusercontent.com/assets/2533112/6176853/df33311c-b2b6-11e4-89c7-2a0cd06a68ce.png)

![leader-signature](https://cloud.githubusercontent.com/assets/2533112/6176856/e11cfa58-b2b6-11e4-8fb3-698e47f6521e.png)

![c4-signature](https://cloud.githubusercontent.com/assets/2533112/6176858/e417a41a-b2b6-11e4-885b-6db85e8ac55a.png)

**Comment by lippytak** [comment]
Possible windows RT fix documented here: https://github.com/brinley/jSignature/issues/29

Also worth testing using the official demo to see if our code may be causing the problem: http://willowsystems.github.io/jSignature/#/demo/

**Comment by lippytak** [comment]
Motivation from a user Lisa: https://github.com/codeforamerica/health/wiki/User-research#20150217-lisa-at-meda

**Comment by lippytak** [comment]
Summary of my convo with our friendly neighborhood lawyer, Deven:
-  We can do e-sig in CA
- Checkbox + typed name + store the data (date, name, checkbox, etc.) more than suffices
- See below for more info she sent along

We're done with research. Next step is to make it happen: https://github.com/codeforamerica/clean/issues/375

> Link to the California Uniform Electronic Transactions Act - http://www.leginfo.ca.gov/cgi-bin/displaycode?section=civ&group=01001-02000&file=1633.1-1633.17  See section 1633.2(h) for the definition of what constitutes an electronic signature; 1633.4 (applies to any electronic record generated sent or stored after 1/1/2000); 1633.5(b) applies to transactions where both parties have agreed to conduct the transaction electronically, and such agreement is determined by context and surrounding circumstances, including actual conduct; 1633.7 (a record may not be denied legal effect or enforceability solely because it is in electronic form); 1633.9(a) – an electronic signature is attributable to a person if it was the act of a person, which may be shown “in any manner” (no id proofing required). 
 
> Letter from DSS instructing counties to accept telephonic signatures - http://www.dss.cahwnet.gov/lettersnotices/EntRes/getinfo/acin/2013/I-60_13.pdf
 
> I also found this in my own research, which seem to be an online application for CalFRESH:  http://www.benefitsapplication.com/program_info/CA/CalFresh?gclid=Cj0KEQiA37CnBRChp7e-pM2Mzp0BEiQAlSxQCAL1dqc-ONF6c0xrK34JMctV_hWWQ-PkqjCAzEyKek8aAlgo8P8HAQ

**Comment by daguar** [comment]
Sweet — @lippytak, mind migrating the info/links to the Wiki as well?

(As incentive, I will reopen this issue. :D )

**Comment by lippytak** [comment]
Great call will do.

**Comment by lippytak** [comment]
https://github.com/codeforamerica/health/wiki/Research#electronic-signatures-in-ca
