### ISSUE TITLE
Give feedback on file upload 

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#328]
"you could give me a game to play or something" - Francesca.

On Francesca's phone, the default web browser indicator that a file uploading is occurring is minimal. While the state of our button changes and the copy communicates that things are processing, we need to give a far better and confidence-building experience while the assister is waiting for upload to complete.

**Comment by daguar** [comment]
Robot animation.


On Wed, Feb 11, 2015 at 3:40 PM, Alan Joseph Williams <
notifications@github.com> wrote:

> "you could give me a game to play or something" - Francesca.
>
> On Francesca's phone, the default web browser indicator that a file
> uploading is occurring is minimal. While the state of our button changes
> and the copy communicates that things are processing, we need to give a far
> better and confidence-building experience while the assister is waiting for
> upload to complete.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/328>.
>



-- 
Dave Guarino
Engineer, Health
(2013 Fellowship alumnus)
Code for America <http://www.codeforamerica.org/>
dave@codeforamerica.org
LinkedIn <http://www.linkedin.com/in/daveguarino/> | GitHub
<https://github.com/daguar/>

**Comment by lippytak** [comment]
Don't make them wait (seriously...we should start doing BG processes soon)
