### ISSUE TITLE
Drop Medi-Cal

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#332]
There are problems:
- ELE is being applied inconsistently at best in terms of internal biz process.
- Not everyone is eligible for ELE but if your ELE request is denied nobody ever tells you...silence
- If you're on MC through ELE and you lose CF then you also lose MC...not ideal
- If you already had an active MC case that has been closed, I don't think 

Overall it's impossible to explain this to CBOs/clients in a way they can easily understand and take action on. I vote we remove this and further clarify the value prop - "Apply for CalFresh in 10 mins"

**Comment by daguar** [comment]
I agree, and this is pretty easy.

@alanjosephwilliams — if you give the :+1:, I'll go ahead and tee this up.

**Comment by lippytak** [comment]
Discussed and ready to Make It So!

**Comment by alanjosephwilliams** [comment]
Indeed. I see no dependencies. Let's clarify our value proposition yo.

**Comment by daguar** [comment]
EFF YEAH MOFOS
