### ISSUE TITLE
EBF action plan

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#335]
- [x] @alanjosephwilliams will build 'help page' alternative to doc upload
- [ ] @daguar will merge/push it
- [x] @lippytak will writeup the big bugs right now (#333 #331 #327)
- [x] @lippytak will email Food Bank + all current Clean users to give them FYI and call me if any concerns
- [x] @lippytak will let RM know what to expect in terms of emails
- [x] @lippytak will go get $25 gift cards for Xiao and Francesca today
- [x] @lippytak will put in order for $10 gift cards for users going forward

**Comment by daguar** [comment]
Fix pushed

**Comment by lippytak** [comment]
Great job @daguar @ajw @RebeccaCoelius !
