### ISSUE TITLE
Store verification documents and send links to HSA (not attachments)

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#341]
We've experienced the pain of submitting verification documents by creating giant attachments and sending over email to the agency ( #333, #331 ). SendGrid limits us to ~20mb emails, and even if they didn't, we'd hit major issues relatively soon with big attachments.

Here's what I think the an MVP spec for this looks like:

- User flow:
 - Same flow for as now for the applicant/assistor
 - For the agency receiving the email, they would now receive an email with a URL instead of an attachment: the URL would still be for a password-protected zip file, but that zip file would contain two PDFs (application + verification documents)
- Backend:
 - Store as binary data in Postgres (or S3, though I have some security concerns there)

Random questions:
- Do we combine all the documents into one like before? Or do we just give individual files? (Which may be higher quality, since no Imagemagick conversion occurs.)
- *Securing the files*
 - Do we make downloading the files require some sort of login? (basic authentication? actual login system for agencies? I'd vote basic auth at max for now.)
 - Do we password-protect the files (like an encrypted, password-protected zip as currently?)
 - Or do we do the minimum: provide an obfuscated URL over HTTPS (I don't recommend this; seems too insecure.)
- How long do we store files for?
- Should we use S3, or store the files as binary data in Postgres? (I'd probably vote S3, but some security considerations.)
- Do we put both the application and the verification documents in the same zip file? Or do we want to attach the application and use a URL for the documents only?

**Comment by lippytak** [comment]
IMO:
- S3 for availability -if we go down HSA should still be able to process apps
- Basic auth - seems comparable to what we're doing now (obscurity + shared pass among same people)
- Permanent storage for now - easy to change in the future and our lawyer recommended being conservative in our privacy policy anyway
- Application and docs in the same file - RM has a pretty rough experience right now and they mentioned today it felt very error prone having the emails separated. They're certain they will make mistakes as volume increases.

**Comment by lippytak** [comment]
And not to mix issues but this may be a good time to redo the frontend (or a bad time?). For starters we should probably allow multiple file selection so users don't have to repeat the same flow over and over. We could use something like: https://blueimp.github.io/jQuery-File-Upload/ (supports all our things: https://github.com/blueimp/jQuery-File-Upload#browsers) but not sure how it interacts with camera etc.

**Comment by lippytak** [comment]
ALSO (mixing in more things) I spoke to one user (Lisa) and Records Management today and both convos made me think we should incorporate the doc upload process into the core application flow. Whether or not we want to separate them technically  I don't think users think of this as a separate part of the application so it's a bit weird to say YOU'RE DONE! (now keep going). Also on the internal side having the application + verification docs together in  a single file would be better for them.

We can parse these out into separate issues when we start working on them.

**Comment by alanjosephwilliams** [comment]
strong agree on re-working this flow to improve the user experience

**Comment by lippytak** [comment]
Subsumed by https://github.com/codeforamerica/clean/issues/365. Feel free to reopen if you'd like to keep this separated.
