### ISSUE TITLE
Remove placeholders for date format

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/clean#342]
We moved away from using form placeholder text, which is supported unevenly across the browsers of our current users. We are, however, still using it to describe the required format for dates of birth. Let's move away from it in that use case as well. We have a `form-context` style defined for exactly this situation.

**Comment by daguar** [comment]
When this happens, could we also suggest users use MM/DD/YY (ie, 2-digit year)?

We can accept and process 4-digit year, but 2-digit year is preferred. Any big UX considerations one way or the other?

**Comment by alanjosephwilliams** [comment]
Both of these suggestions are addressed in #358

**Comment by daguar** [comment]
Closed by merge of #358
