### ISSUE TITLE
Marketing assets

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#351]
- Wallet card for clients
- Screener/reference card for assisters

@alanjosephwilliams let's discuss. Feels like too much for you this sprint but I could own copy audit or something.

**Comment by alanjosephwilliams** [comment]
wallet card can happen—screener reference cards are a stretch

**Comment by alanjosephwilliams** [comment]
if you wanted to take a pass at copy for reference cards that would be awesome.

**Comment by lippytak** [comment]
@alanjosephwilliams - drop for this sprint?

**Comment by alanjosephwilliams** [comment]
Let's drop it. If it gets done its lagniappe.

On Tue, Feb 17, 2015 at 4:10 PM, Jake Solomon <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> - drop for
> this sprint?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/351#issuecomment-74784169>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
