### ISSUE TITLE
End with printable confirmation page

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#355]
That acts as a receipt + next step reference for clients. See user Lisa for the motivation: https://github.com/codeforamerica/health/wiki/User-research#20150217-lisa-at-meda

This may be v1 of what turns into downloading a full copy of the app (https://github.com/codeforamerica/clean/issues/126)

**Comment by lippytak** [comment]
See CC example: https://files.slack.com/files-pri/T024F66L9-F03RS9B2A/download/application_receipt_contra_costa.pdf

**Comment by daguar** [comment]
Re-assigning back to you @alanjosephwilliams after discussion in the PR (just for Waffle housecleaning)

**Comment by lippytak** [comment]
"They echo the ask for a confirmation page… so just putting that out there." MEDA + FB request again. 

Could be a good opp for user testing: https://github.com/codeforamerica/clean/issues/461

**Comment by lippytak** [comment]
+1 from Lisa at MEDA: "One more thing. Can you pleeeeaasseeeeee make a confirmation number so clients have something when they leave? Everyone asks for it!"

**Comment by daguar** [comment]
@lippytak I'd love to see if we can ship a super MVP version of this quickly this week. Here's how I'd propose to do it:

- Final page is printable, has instructions on next steps
- Final page has a "confirmation #" that is basically just a unique # and we store it in the database for that case

Here's my question — won't the clients have a bad experience if they're given a confirmation # and they talk to HSA and HSA's like "wtf"?

**Comment by daguar** [comment]
OKAY! Chatted IRL as a group, and we're gonna wait until after doc upload is done because we need to better understand the actual user need (proof of submission? ability to show to HSA proof of it? follow-up?)

**Comment by lippytak** [comment]
@alanjosephwilliams can we have v1 ready to go by EOW since the current confirmation page won't make sense once doc upload is back?  Let's chat if you think that might not work and I can tag in on some of the work.

**Comment by alanjosephwilliams** [comment]
No doubt we can have it ready to go.

On Mon, Apr 20, 2015 at 5:28 PM, Jake Solomon <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> can we have
> v1 ready to go by EOW since the current confirmation page won't make sense
> once doc upload is back? Let's chat if you think that might not work and I
> can tag in on some of the work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/355#issuecomment-94591794>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
May want to consider 'do another application' button in the design for this final page https://github.com/codeforamerica/clean/issues/490

**Comment by alanjosephwilliams** [comment]
#523 makes progress on this front

**Comment by alanjosephwilliams** [comment]
This is first priority of the week.

**Comment by alanjosephwilliams** [comment]
We solicited feedback from the Food Bank team on this sketch last week:
![img_3004](https://cloud.githubusercontent.com/assets/2983464/7508903/ced78c6c-f44e-11e4-9eee-783f82b41107.jpg)

**Comment by alanjosephwilliams** [comment]
We received some great feedback from the FB:
- Everyone likes the proposed layout
   - “very clean”
- Still no choice for in person appointment?
- Under what’s next:
   - add time frame for when to expect call from HSA (ex. Within 10 days)
   - perhaps some info about how long interview could take (approx. 20 min)
- Add 30 day legally required benefits determination—gives client context for how long process can take and can nudge them to check in on process /complete their responsibilities within specific time frame

- Keep in touch with your assister
   - A lot of questions about rollout to partner agencies vs. individuals
   - Currently not many of our partners are really completing follow up more than once after initial application
   - Problem solving happens through us –although our plan is to create more capacity and systems to make follow up feasible
   - Don’t want to set unreasonable expectation for clients that more fu will occur
   - perhaps could instruct client to call assister after X days  and/or when issues arise
- Automated follow up:
   - Will client get email/text with confirmation of application date, verifications turned in/missing, instructions?
- Assister follow up:
   - Will the screen be printable/pdf for assister’s using the site?
   - For those assisters that are mobile /working off laptops or tablets—will there be functionality to download page to email to clients
   - Alternatively we discussed just having these type of assisters print out many copies of the page and handwrite in fu info

**Comment by alanjosephwilliams** [comment]
We've incorporated the majority of the feedback, and we are honing in a good v1. The biggest improvements will come from (a) getting the copy really dialed in, helping people and setting expectations in just the right way and (b) getting some solid iconography. 

I think that we should go ahead and solicit the Food Bank's feedback on this. For example—they may suggest that we offer a path to escalation _to them_ for assisters to promote if they aren't comfortable doing follow up themselves. 

#### Web Version
![confirmation_page_web](https://cloud.githubusercontent.com/assets/2983464/7508922/558e59e8-f44f-11e4-8760-3b3d8592d1d3.png)

#### Mobile Version

![confirmation_page_mobile](https://cloud.githubusercontent.com/assets/2983464/7508946/c252e026-f44f-11e4-8336-fbc265eedd69.png)

#### Print Version

![confirmation_page_print](https://cloud.githubusercontent.com/assets/2983464/7508948/c9ed3732-f44f-11e4-9157-abda5e6f6062.jpg)

#### Email (WIP)

![screenshot 2015-05-07 00 28 29](https://cloud.githubusercontent.com/assets/2983464/7508960/15930842-f450-11e4-9558-e0b11eb638d0.png)
