### ISSUE TITLE
Concierge cases

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#367]
Someone replied to our survey. I'll contact them this afternoon/evening and do my best to help them apply.

**Comment by alanjosephwilliams** [comment]
Are we receiving these survey responses at health-lab?

On Mon, Feb 23, 2015 at 2:14 PM, Jake Solomon <notifications@github.com>
wrote:

> Someone replied to our survey. I'll contact them this afternoon/evening
> and do my best to help them apply.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/367>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Finally got in touch with this person. Lives in Oakland, works two part time jobs, almost certainly eligible though she may have to apply with her parents...tricky living situation. She's going to try BCW and call/text me with questions. She was so nice...

Everyone who works a minimum wage job in SF should apply for CF. Outreach opportunity.

**Comment by alanjosephwilliams** [comment]
Big :+1:
