### ISSUE TITLE
Homepage misc nitpicks

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#368]
- 'Get extra...' instead of 'Receive extra...'
- Confusing that one header is monthly and the other is annually
- 'Apply' instead of 'get started'
- ~5-6 font styles is a visually jarring (to me)
- Email address to href

![screen shot 2015-02-23 at 2 43 01 pm](https://cloud.githubusercontent.com/assets/2533112/6339442/f011ad4e-bb6a-11e4-82e3-fb01ee24fd31.png)

**Comment by alanjosephwilliams** [comment]
All of these are addressed in #372
