### ISSUE TITLE
Implement e-signature

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#375]
- [x] Remove current jSignature code
- [x] Replace signature view with form inputs for name and 'agree' checkbox
- [x] Add migration
- [x] Save signature data to the DB (name, checkbox status)
- [x] Print signature to CF-285
- [x] Print signature to ROI
- [x] Write tests
- [x] Update cover page to explicitly address that the sig may look weird but it's valid
- [x] Review with Leo
- [x] Rebase and PR

Research: https://github.com/codeforamerica/clean/issues/326

Working on: https://github.com/codeforamerica/clean/tree/e-signature

**Comment by lippytak** [comment]
^ updated with the steps to implement

**Comment by daguar** [comment]
Maybe we review with Leo first? Based on current level of EW confusion, I think it makes sense to check in first before putting in the effort — it may change the requirements.

How did the Intuit applications deal with this, btw?

**Comment by daguar** [comment]
Moved this to current sprint — Jake, are you doing the front end stuff here or am I? I know some of the backend stuff I need to do, so let's just touch base and break out into separate issues if necessary.

**Comment by lippytak** [comment]
Will be working on here: https://github.com/codeforamerica/clean/tree/e-signature. All I've done so far is delete all the jSignature remnants.

**Comment by daguar** [comment]
I rebased against master, so the e-sig working branch now has all the backend storage work in it.
