### ISSUE TITLE
Investigate Carissa application error

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#380]
She got an app error when clicking submit on a ~3 person case. I believe she tried again and everything worked. I'll review with her today and add more info here, then assign to @daguar to investigate further.

**Comment by daguar** [comment]
I don't see an error in the logs; please let me know the client name and I can look specifically in that area.

**Comment by lippytak** [comment]
She got busy Fri so we'll discuss Mon over lunch

**Comment by lippytak** [comment]
- "Application error" (generic heroku error it sounded like)
- Using iPad
- Family of 4
- 3g connection
- Turns out the application actually went through successfully

I'm thinking Heroku timeout.

@daguar ideas?

**Comment by daguar** [comment]
Yup, I see a Heroku R12 (platform timeout) in the logs twice — looks like she hit refresh after the error to submit again. Regardless, it submitted (twice; assume that's not a big issue?) I'm messaging you the client name to confirm.

The real fix here is moving this to a background job ( #349 which I've done on a branch already... :winkyface: )

**Comment by alanjosephwilliams** [comment]
Do we know what view/screen she saw on error? Did she get the 500 page?

On Wed, Mar 4, 2015 at 11:48 PM, Dave Guarino <notifications@github.com>
wrote:

> Yup, I see a Heroku R12 (platform timeout) in the logs twice — looks like
> she hit refresh after the error to submit again. Regardless, it submitted
> (twice; assume that's not a big issue?) I'm messaging you the client name
> to confirm.
>
> The real fix here is moving this to a background job ( #349
> <https://github.com/codeforamerica/clean/issues/349> which I've done on a
> branch already... :winkyface: )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/380#issuecomment-77320703>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Per above, sounds like she got the generic Heroku error page (because a Heroku platform timeout means our app didn't respond within 30 seconds of the request; so it wouldn't have responded with the 500 page.)
