### ISSUE TITLE
Info sharing copy edits

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#386]
Feedback from EDC case workers on https://demo.cleanassist.org/application/info_sharing:
- 'Caring for your case' weird and vague - be more direct
- What does 'Reasons for cases judgements' mean?
- What does 'Description of all verification docuemnts' include/not include?
- 'documents' typo above

And some of my own thoughts:
- I think we can cut a lot of the text and keep the main point: "Let CfA access your case information so we can make sure your case is treated right."
- Include VM in contact prefs 'can we leave a voicemail about CalFresh?' or something
- I don't think people are going to be able to distinguish between "we" and HSA...not sure what to do about this but just something to consider

And a couple tweaks to the actual ROI form:
- Add Leo's name/signature/contact info
- Add time limit on release (1 year unless there's a good reason for something else)

**Comment by daguar** [comment]
Corollary thing — this is, in a way, usability feedback from real users.

I wonder if we could do user testing of the cover sheet with an EW or two?

**Comment by lippytak** [comment]
And a couple tweaks to the actual ROI form:
- Add Leo's name/signature/contact info
- Add time limit on release (1 year unless there's a good reason for something else)

**Comment by lippytak** [comment]
Noting from doc upload user testing with food bank that in general the current ROI is not working well for them. Francesca suggested it come first because it would be easier to review with clients before they start the application. Liliana said she "had to talk around it" recently at WIC. Worth reconsidering if/how we do this and getting their feedback.

**Comment by lippytak** [comment]
Closed PR and moving this back to 'ready'. Next iteration will involve a bit more work and potentially change our workflow with HSA.

**Comment by alanjosephwilliams** [comment]
We did update this and its live on production. Closing for now. We might want to reference this issue if we ever open a new issue for a more "terms of service" style release of information.
