### ISSUE TITLE
DOB validation is styled differently

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#390]
![screen shot 2015-03-02 at 2 45 56 pm](https://cloud.githubusercontent.com/assets/2533112/6452508/f494f1ca-c0ea-11e4-9d94-3bb45caabd54.png)

**Comment by daguar** [comment]
It's not a different styling per se, it's that we don't use Parsley right now for validating this field (but we DO have the HTML5 "required" flag here.) Not too hard to fix.
