### ISSUE TITLE
Look into missing verification docs

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#391]
Some recent MEDA users are missing verification docs. I'll research/confirm current internal biz process. Can't wait for overall better doc upload process!

**Comment by daguar** [comment]
I FEEL PAINNN

**Comment by lippytak** [comment]
Confirmed with records mgmt that current internal biz process is working. Advised Lisa to use food@sfgov to re-send old confirmations when necessary and send specific problem cases to Liliana and I.
