### ISSUE TITLE
Clean up date validation/processing

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#397]
It's gross, has caused problems before, and we have better solutions.

This will involve:
- Writing more tests for different date edge cases
- Validate date input more rigorously (using the `Chronic` library) on the server side at the point of input by the user
- Deleting old, parser-based logic for dates (duplicated in at least 2 places)

**Comment by lippytak** [comment]
I ran into this case today: 3-3-12 parses on the front-end but blows things up upon submission.
