### ISSUE TITLE
Server time != PDT

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#401]
Our application dates are sometimes 1 day ahead. Getting the application date right is important because that's when your benefits start once you are approved (and other things).

I think this is because our server time != PDT (UTC?) but haven't confirmed.

**Comment by lippytak** [comment]
Note from Louisa at HSA: "Application was received on 3/3/15 at 4:43 pm but the CF 285 reflects another date, 3/04/15."

**Comment by daguar** [comment]
The issue was that by default Ruby's internals use UTC, so we're moving to Rails' nice helper that lets you config the app for a timezone, done in #403.
