### ISSUE TITLE
Frontend debt payment

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#412]

**Comment by lippytak** [comment]
Stub! @alanjosephwilliams plz specify what you'd like to take care of this week or feel free to close and defer the payment.

**Comment by alanjosephwilliams** [comment]
In order of priority:
1. Always Be Improving Our Copywriting.
2. Improve our integration tests.
3. It's time for more modular markup. 
4. Continue to optimize/bring consistency to our SCSS.

**Comment by lippytak** [comment]
Moving off sprint this week.

**Comment by alanjosephwilliams** [comment]
This will be closed with #355 is merged.

**Comment by alanjosephwilliams** [comment]
(for now, obv)
