### ISSUE TITLE
Help wufoo respondent apply for CalFresh

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#425]
See your email: Get help applying for CalFresh in San Francisco [#2]

Be prepared to screen them and direct them to the best application pathway given their situation.

**Comment by lippytak** [comment]
Done? If not let's do this soon. Feel free to reassign to me if you want.

**Comment by lippytak** [comment]
Emailed (their contact pref). Will FU as necessary.

**Comment by daguar** [comment]
:+1: thanks!
