### ISSUE TITLE
Concierge plan v2

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#427]
Carissa track more data? Ebt card usage?

Specifically what to do about Spanish/Cantonese follow up?

**Comment by lippytak** [comment]
Include specific enough instructions that a new comer (Gabby) can try a few!

**Comment by alanjosephwilliams** [comment]
We'll want to add the date the application was submitted to our concierge workflow. This has been requested by the EW retrieving case information a few times. Seems like it cut down on some ambiguity and help retrieve and report case status faster.

**Comment by lippytak** [comment]
More data to track:
- EBT issue type /date
- EBT first use date
- Docs in iFiles
- Cold call status

**Comment by lippytak** [comment]
- benefit AMOUNT

**Comment by lippytak** [comment]
Better place for feedback

**Comment by lippytak** [comment]
Updated clean-cases spreadsheet to track more info.

Added feedback instructions for the team: https://github.com/codeforamerica/clean/wiki/How-to-do-case-follow-up#feedbackproblemsquestions

cc @gabbyjones @daguar @alanjosephwilliams
