### ISSUE TITLE
Deal with Mickey Mouse case submitted

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#439]
It looks like someone submitted a dummy case on production — do we want to do anything to communicate to HSA that it's a dummy? Remove it from the DB? Any other steps?

**Comment by lippytak** [comment]
I notified RM so I think we're all good here.

Feel free to delete @daguar if you think that's the right thing. I'm agnostic...though we'll always be getting *some* bad data so not sure we should manually delete as a matter of policy.

**Comment by daguar** [comment]
I'll leave it for now — good to have the record, and we can always delete (or mark) later.
