### ISSUE TITLE
ECF: MEDA February cases

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#452]
Emergency Case Fix (ECF)! Only ~25% of MEDA cases in Feb were approved. I have a list of these cases. Let's fix 'em:
- [x] Work with Carissa to figure out exactly why each case was denied
- [x] Send info to FB
- [x] Jake look into one ghost case (never cleared)
- [x] Take MEDA out for lunch for their awesome work helping os many families get CalFresh!

**Comment by alanjosephwilliams** [comment]
:+1: I'll help row this boat for a couple hours this morning as well.

On Sat, Mar 28, 2015 at 5:09 PM, Jake Solomon <notifications@github.com>
wrote:

> Emergency Case Fix (ECF)! Only ~25% of MEDA cases in Feb were approved. I
> have a list of these cases. Let's fix 'em:
> 1. Do case research to figure out exactly why each one was denied
> 2. Reapply for folks who missed interviews
> 3. Submit/resubmit verifications for folks with missing docs (we still
> have ~30 days to get docs in and Lisa should have copies of most)
> 4. Take MEDA peeps out to lunch for their awesome work helping so many
> families get CalFresh!
>
> @daguar <https://github.com/daguar> let's touch base Mon AM and figure
> out the plan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/452>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Per discussion on Slack, can't really do this in a multi-pronged way yet because we need denial reasons first, and then to get those to MEDA to do some targeted follow-up (with us). Will also work with the FB with MEDA.

**Comment by daguar** [comment]
Maybe one additional step in the process — for any clients where we've created a particularly negative experience, provide gift cards?

**Comment by lippytak** [comment]
Updated original issue to show that our job is to provide FB with info here - they'll interface with MEDA for case FU and training stuff.

**Comment by lippytak** [comment]
Emailed about the ghost case...

**Comment by lippytak** [comment]
Food bank officially has this Under Control.
