### ISSUE TITLE
Clean ID 16 treated poorly and told to do MBCW

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#457]

**Comment by lippytak** [comment]
Just got a call from Lisa saying her client spoke to an EW in the AM who was really rude, said Clean wasn't a real app and that she needed to do MBCW. I'll FU with HSA + Lisa and report back here. FYI @alanjosephwilliams you were assigned FU for this case but I'll take it for now as part of escalation.

**Comment by daguar** [comment]
:+1: we need to escalate to HSA in a serious way; this is not okay.

**Comment by lippytak** [comment]
Serendipitously I discussed w EW who took the call. BLUF is that the EW (and her supervisor) think the clients needs to submit and sign a "full" application, which seems to mean many different things.

Action items
- [ ] I'll escalate case to James to make sure client isn't asked to do more
- [ ] I'll raise training/awareness issue to Leo/Tiana, ask them to clarify federal law (argh hah) with Seciton Managers/Supervisors/EWs
- [ ] I'll ask Tiana to email Lisa personally to legitimize and apologize

I'll consider this closed when the case is approved/determined and Lisa gets a personal note from HSA.

**Comment by danhon** [comment]
What's an MBCW? How can I help?

**Comment by daguar** [comment]
@danhon Sorry! I think it was a mistaken mention with the autocomplete for "dave"

(Though content suggestions on how to distribute changes in eligibility/policy to front-line workers would be welcome...)

**Comment by lippytak** [comment]
oops sorry @danhon . Wrong @ mention!

**Comment by lippytak** [comment]
Carissa dug into this a bit and it looks like they don't even have the 3 page CF-285 on file. (Q-Flow nor iFiles) If so, that explains a lot and it makes the EWs perspective much more understandable. Not sure how I missed this on the phone call! I messaged RM to see if they have a copy of the CF-285 application to get that processed and we'll do a quick after action review to see where/why it got lost. I suspect this is just human error so having docs + application integrated into one PDF/email will solve this one.

**Comment by lippytak** [comment]
Original CF-285 FOUND! Human error I believe. It's being processed now and hopefully everything can be squared away before client interview tomorrow PM.

**Comment by alanjosephwilliams** [comment]
This is not the first/only case where we have no CF-285 on record for the
client. Do we know where the CF-285 was found? If so, that might be helpful
guidance to give an EW next time the problem occurs.

On Wed, Apr 1, 2015 at 7:45 PM, Jake Solomon <notifications@github.com>
wrote:

> Original CF-285 FOUND! Human error I believe. It's being processed now and
> hopefully everything can be squared away before client interview tomorrow
> PM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/457#issuecomment-88665077>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Case is approved and Tiana sent a personal email to MEDA. Done!
