### ISSUE TITLE
interaction design: signature field

### ISSUE THREAD

**Issue by cydharrell** [codeforamerica/clean#46]
I'm not sure exactly what should happen, but this seems like a critical interaction. Make it great on a crummy phone and you're winning. This may involve instructing people to turn their phone to landscape orientation, or really refining the area the signature needs to be in and highlighting with a box, or having them get a pen to use instead of a finger... it needs to feel really comfortable and be easy.

**Comment by alanjosephwilliams** [comment]
This is still a problem. Last we discussed, I remember something akin to consensus that a typed signature would be valid. Certainly, when using a laptop or desktop, typing your name as a signature is easier than using the trackpad.

**Comment by daguar** [comment]
I'd love to double down effort on interaction in Clean -- seems like after the rewrite we'll have a more solid foundation to do this (eg, integration test coverage for JS interactions.)

**Comment by lippytak** [comment]
Only way to do this well for our users is to kill it - see https://github.com/codeforamerica/clean/issues/326 for progress.
