### ISSUE TITLE
Setup online ads

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#479]
Let's test online ads across a few dimensions:
- Platform
- Keyword groups
- Survey interface (sms vs web form)

Template for final stats: https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1vfjxik5oYBRnm4ssXVoR5H7aYwuNWLbUr2yqIRp8fZU/edit#gid=0

**Setup**
- TypeForm
  - [x] Build it
  - [x] QA It
  - [x] get it on getcalfresh.com
  - [x] Test invisible fields/sources
- Textit.in
  - [x] Build it
  - [x] QA it
  - [x] Landing page on getcalfresh.org
  - [x] Auto respond with 'Need help? Email support@'
  - [x] Write Twilio app with one route that sends a welcome text to a number
- Zendesk
  - [x] Setup Zendesk email (support@getcalfresh.zendesk.com)
  - [x] Config 10 day FU view
  - [x] Config new email > new ticket
  - [x] Config NO accidental emails to users
  - [x] Add team to ZenDesk
- Ticket integration
  - [x] Setup TypeForm > Zendesk ticket in the FU view
  - [x] Setup Textit.in > Zendesk ticket (can use email)
- Setup Ads
  - Remember to set source='adgroup_name' in URL
  - SMS interface should target mobile only
  - English / California
  - [x] Google
  - [x] Facebook
  - [x] Twitter
  - [x] Bing
  - [x] QA ads (review together)

**Comment by lippytak** [comment]
Mini twilio app fun + textit.in flow

![screen shot 2015-04-13 at 3 42 28 pm](https://cloud.githubusercontent.com/assets/2533112/7127058/d28da3fe-e1f3-11e4-9b4e-c40a05c52006.png)

**Comment by alanjosephwilliams** [comment]
Documenting some of the limitations of Typeform: 
- We can't validate whether or not a ZIP is in California.
- We can't validate phone numbers.
- The asset question felt like a lot to answer.

**Comment by alanjosephwilliams** [comment]
Skeleton input buttons are FUBAR on iPhone 5.

**Comment by lippytak** [comment]
Textit.in
- Remove savings on both
- Drop email

**Comment by alanjosephwilliams** [comment]
new pages with boostrap instead of skeleton shipped.

**Comment by alanjosephwilliams** [comment]
Facebook Ads:
- Targeting people with net worth between $1 - $100,000
- Californians
- 18 to 65+
- English only

We still have work to do to get our URL params successfully to typeform:
- generate the param detailing the source of the user
- replace the existing iframe src to include that param
- capture it successfully with hidden form field.

**Comment by alanjosephwilliams** [comment]
URL params are successfully being recorded by typeform, and being generated by Facebook Ads.

**Comment by lippytak** [comment]
ADS ACTIVATED. More info to come soon. Good days work @alanjosephwilliams :thumbsup:
