### ISSUE TITLE
QA document upload

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#486]
DO IT

**Comment by lippytak** [comment]
Just some notes as I go. I'll turn these into issues or a checklist when done:
- If you click 'next step' before docs are finished uploading bad things happen.

**Comment by alanjosephwilliams** [comment]
Liliana tried to upload a powerpoint :)
![doc_upload_powerpoint](https://cloud.githubusercontent.com/assets/2983464/7213777/08c77452-e548-11e4-84cb-917480e4a779.png)

**Comment by lippytak** [comment]
Got stuck when uploading ~25 files
![screen shot 2015-04-18 at 6 44 03 am](https://cloud.githubusercontent.com/assets/2533112/7215659/f4bd270a-e596-11e4-84c4-b9c201498aa2.png)

**Comment by lippytak** [comment]
Error logs on mobile after 'Submit App' > 
> 2015-04-18T14:38:55.302283+00:00 app[web.1]: UUID: 1401433864075802802
2015-04-18T14:38:55.302285+00:00 app[web.1]: URL:  https://airbrake.io/locate/1401433864075802802
2015-04-18T14:38:55.303566+00:00 app[web.1]:
2015-04-18T14:38:55.303569+00:00 app[web.1]: NoMethodError (undefined method `length' for nil:NilClass):
2015-04-18T14:38:55.303572+00:00 app[web.1]:   app/controllers/application_controller.rb:163:in `review_and_submit_submi

**Comment by lippytak** [comment]
UI issue with long filenames:
![screen shot 2015-04-18 at 7 46 03 am](https://cloud.githubusercontent.com/assets/2533112/7215897/23ce48aa-e59f-11e4-8e73-3a3bf030e208.png)

**Comment by lippytak** [comment]
Uploads get stuck ~5% of the time:
![2015-04-18 17 16 55](https://cloud.githubusercontent.com/assets/2533112/7217581/19dca74e-e5e8-11e4-8322-c19a0304ca05.png)

**Comment by lippytak** [comment]
P1/P2 bugs are now issues: https://github.com/codeforamerica/clean/issues/494 https://github.com/codeforamerica/clean/issues/495 https://github.com/codeforamerica/clean/issues/496 https://github.com/codeforamerica/clean/issues/497 and https://github.com/codeforamerica/clean/issues/498

And the release checklist in the OG issue: https://github.com/codeforamerica/clean/issues/365

**Comment by daguar** [comment]
Checked off Windows RT because Liliana tested it

**Comment by daguar** [comment]
@lippytak there's a few more unchecked QA boxes above; should we re-open this?
