### ISSUE TITLE
Improve document upload resizing to maintain quality

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#487]

**Comment by daguar** [comment]
cc @lippytak

**Comment by lippytak** [comment]
Not only do we lose quality on the Image.fit but it takes a long time...just tried it locally with a multi-color image with lots of small text and it took ~2 mins to run.

**Comment by lippytak** [comment]
Relevant: https://github.com/prawnpdf/prawn/issues/811

Also I'm finding through trial and error that Unsharped Resizing (USM) (http://www.imagemagick.org/Usage/resize/) is yielding more legible images for text-heavy docs. Not sure if MiniMagick can do this but on the command line it's: `convert "type.jpg" -filter spline -resize 500x500\! -unsharp 0x1  output_unsharp.png`

**Comment by lippytak** [comment]
So I'm having trouble finding a problematic example right now (all my inputs look good just using `prawn_pdf_doc.image("input_text.jpg", fit: [500, 500])`

But I think we can fix this by increasing DPI and then resampling and resizing using MiniMagick first:
```
# Increase DPI & resample in place
image = MiniMagick::Image.new("input.jpg")
image.density "300"
image.resample "300"
image.resize "500x500"
```

@daguar show me a bad example locally and then we can try this solution.

**Comment by daguar** [comment]
I think I've isolated the source of the quality loss — it's not Prawn, it's using Imagemagick's raw `convert` command in shell to convert. Previously we've addressed this by using PDFtk's cat command, so I'll try that now.

**Comment by daguar** [comment]
Done! Fixed via https://github.com/codeforamerica/clean/commit/a3eab863c292378739e253456a594a7fa83e0084
