### ISSUE TITLE
FU with engagement test group

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#491]
Context: https://github.com/codeforamerica/clean/issues/483

- [x] Create template follow up via email/mms/voice. Email survey template + Textit.in FLOW that we would start.
- [x] Do 10 day FU with HSAs for data collection
- [x] Do 30 day FU with HSAs for data collection
- [x] Do 30 day FU with all applicants for qualitative interviews
- [x] Track teh dataz (https://docs.google.com/a/codeforamerica.org/spreadsheets/d/1N_pGFb7SOte4EJEM15Va3_-wDFQvoYamwX9iTNSylIM/edit#gid=9788676730)
- [ ] Qualitative phone interviews
- [ ] Writeup

**Comment by lippytak** [comment]
Decided to do HSA-only calls for ~10 day data collection, at least for the 18 cases where Alan is AR. We'll plan to do client FU at day 30 for qualitative interviews. We'll work out details in sprint planning tomorrow.

**Comment by lippytak** [comment]
Three remaining steps:
- Finish data collection via client contact
- Make It Right with the ~4 barfed cases
- Qualitative interviews with as many as possible in the next 1-2 days

**Comment by daguar** [comment]
Updated the 3 remaining steps comment above.

- We've finished data collection
- We probably did what we can for barfed cases? But maybe we try a few more calls
- Qualitative interview almost done

**Comment by lippytak** [comment]
Data after ~50 days:

We had 18 submitted apps:
- 9 denied
- 5 approved
- 4 unknown

9 denied reasons:
- 5 missing verifications
- 1 (likely) missed interview
- 1 ineligible (must apply with mother)
- 2 unknown

**Comment by lippytak** [comment]
@alanjosephwilliams is going to do one final user research call today but then we're done (unless @alanjosephwilliams wants to try one more contact for the BARFED cases).

**Comment by alanjosephwilliams** [comment]
I will do both today

On Mon, Jun 8, 2015 at 12:19 PM, Jake Solomon <notifications@github.com>
wrote:

> @alanjosephwilliams <https://github.com/alanjosephwilliams> is going to
> do one final user research call today but then we're done (unless
> @alanjosephwilliams <https://github.com/alanjosephwilliams> wants to try
> one more contact for the BARFED cases).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/491#issuecomment-110111721>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
Final FU done. Awesome, useful, successful test. Closing.
