### ISSUE TITLE
Feasibility check driving SAWS

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#492]
Context: https://github.com/codeforamerica/clean/issues/483

Let's check the feasibility of scaling our concierging application approach via browser automation
- [ ] C4
- [ ] MBCW
- [ ] LEADER

**Comment by alanjosephwilliams** [comment]
@lippytak per a lot of our conversations about process last week, along with Atul Gawande's sage advice, maybe you could start to articulate the checklist of tasks to test browser automation here, while Dave and I are revving on doc upload.

**Comment by daguar** [comment]
I'm also realizing this feels slightly premature — do we want to know the results of our manual submissions before going down this road? What's the degree of feasibility we want to know?

**Comment by lippytak** [comment]
Ummm, done :)
