### ISSUE TITLE
Click 'next' before upload finishes == doc does not upload

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#494]
@daguar feel free to reassign to me or @alanjosephwilliams if you think we should just use button styles (http://getbootstrap.com/javascript/#buttons-examples).

**Comment by alanjosephwilliams** [comment]
I'm totally willing to take this one on given our respective concerns. The most obvious solution from my perspective is to simply disable the button until the file uploads.

**Comment by daguar** [comment]
:+1: to that approach @alanjosephwilliams — why don't you take an initial stab and just bug me if you encounter any pushback from our existing JS jank (I think it'll involve some events from the jquery-file-upload, so might be good to pair on it.)

**Comment by daguar** [comment]
I'm taking a quick and dirty stab at this now

**Comment by daguar** [comment]
The JS functionality is implemented ( https://github.com/codeforamerica/clean/commit/4d3e72943ccf8ca38d3731ca76e3a1a09ef5f3e0 )

@alanjosephwilliams Reassigning to you — feel free to either (1) replace those comments with style-change logic or (2) say FISI as-is and I'll just merge this in.
