### ISSUE TITLE
Uploads get stuck

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#495]
Some uploads get stuck and never finish:
- https://github.com/codeforamerica/clean/issues/486#issuecomment-94166280
- https://github.com/codeforamerica/clean/issues/486#issuecomment-94213276

I'll add repro steps here then reassign to @daguar.

**Comment by daguar** [comment]
Could you repro on dev and give a timestamp?

**Comment by lippytak** [comment]
Just uploaded like 50 big fat files twice on diff devices. Even turned wifi off/on mid-upload and everything worked. I'll close and re-open if I can repro or if we hear it from a user.

**Comment by daguar** [comment]
:+1:

**Comment by daguar** [comment]
WE ARE BATTLE TESTED

**Comment by lippytak** [comment]
One got stuck when uploading 20 photos:
![2015-04-27 08 08 02](https://cloud.githubusercontent.com/assets/2533112/7351202/b5105f40-ecb8-11e4-9b45-350129791ce7.png)

After ~3 mins:
![2015-04-27 08 12 02](https://cloud.githubusercontent.com/assets/2533112/7351210/ba5c7c40-ecb8-11e4-891e-c3d481ada7af.png)

'Next' button was grayed out the entire time.

Timestamp for @daguar to check logs (I didn't see anything weird): 8:07 - 8:10am 4/27

**Comment by daguar** [comment]
I believe this is what happened:

`Apr 27 08:05:26 clean-dev heroku/router: at=error code=H15 desc="Idle connection" method=POST path="/uploads" host=clean-dev.herokuapp.com request_id=dd3509e1-5edb-4745-b654-fe1583757a78 fwd="76.14.66.241" dyno=web.1 connect=5ms service=58259ms status=503 bytes=518`

This may happen on occasion and I consider it a cost of doing AJAX business, so don't consider it immediately blocking release.

I think what we _should_ do prior to release is have two different error messages:

1. Our current "bad file format" for unprocessable entity errors
2. "Sorry! There was a problem, try uploading your document again." or something similar for others

**Comment by lippytak** [comment]
Not sure how feasible this would be/what 'idle connection' means exactly,
but it would be good if we could shorten the time here. This one was idle
for 2-3 mins before giving an error, which is painfully long when you're
sitting with a client and the 'next' button is grayed out.

**Comment by daguar** [comment]
@lippytak Were you uploading multiple at the same time? (ie, were you starting an upload, and then starting another before it finished?)

**Comment by lippytak** [comment]
yes

**Comment by daguar** [comment]
Cross-posting, but I've gone ahead and implemented a "try again" error message for any error other than the filetype being bad:

![screen shot 2015-04-27 at 12 25 42 pm](https://cloud.githubusercontent.com/assets/994938/7355875/87f939f2-ecd9-11e4-8cbd-013fc7f0dcfa.png)

**Comment by lippytak** [comment]
@daguar I say let's consider this done for now and re-open if we continue to run into it/get reports from users?

**Comment by daguar** [comment]
Agreed — I just checked, and after a week up with ~7 cases (4 uploading docs) we haven't seen this in the wild.

I've set up an Alert in Papertrail (our logging system) to email us if/when there is an H15 error (which is what we see in the logs when this happens) so we will know proactively if it's happening.
