### ISSUE TITLE
Upload long PDFs > Timeout on app submit

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#496]
For example, try to upload this PDF and submit the application: http://www.knightfoundation.org/media/uploads/publication_pdfs/knight-civic-tech.pdf

Outcome:
> 2015-04-20T23:03:28.796754+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/application/review_and_submit" host=clean-dev.herokuapp.com request_id=65e3548c-9bda-4eb0-874e-a88e53c694bd fwd="69.12.169.82" dyno=web.1 connect=1ms service=30017ms status=503 bytes=0

![screen shot 2015-04-20 at 4 03 30 pm](https://cloud.githubusercontent.com/assets/2533112/7242394/e06eb62e-e776-11e4-8aae-4772f54e529c.png)

Note the application comes through correctly on the backend.

@daguar I'll test to see if this is about big files or long PDFs and distinguish in a comment here.

**Comment by lippytak** [comment]
Actually looks like this is more about long PDFs than big files as I just successfully uploaded 5 ~4MB photos in one go.

Editing the title accordingly.

**Comment by daguar** [comment]
This is a request timeout because it's taking longer than 30 seconds for the file to transfer from S3 and be processed, so a background job should fix this.

**Comment by daguar** [comment]
Confirmed this as fundamentally requiring a background job — heeeeere we go!

**Comment by lippytak** [comment]
Closing - This will be addressed by #349.
