### ISSUE TITLE
Friendly error messages on doc upload

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#497]
Invalid filetype: 
![screen shot 2015-04-20 at 4 13 37 pm](https://cloud.githubusercontent.com/assets/2533112/7242544/3cd78340-e778-11e4-94a0-a172a4f72dad.png)

I've also seen 'internal server error' but can't repro right now. @alanjosephwilliams ping me if you need a repro to figure it out.

Let's make these messages friendly and helpful.

**Comment by alanjosephwilliams** [comment]
:+1:

**Comment by daguar** [comment]
@alanjosephwilliams, this is a pretty small tweak on either the front or backend. If you can give me what you think the most sensical content is I can take on doing it.

I was thinking something like "Oh no! File problem" and maybe we could do some sort of add'l help div?

Related to this: the source of this is when someone uploads a file that's a bad format — I was thinking I'd add some content to the page that says something like "You can upload documents (PDF, JPEG) or take a picture if you're on your phone". Whatchu think?

**Comment by alanjosephwilliams** [comment]
@daguar that sounds about right to me. Wanna quickly pair on this before EOD today?

**Comment by daguar** [comment]
Sorry! Saw this on my run but heading out early because my friend is coming up earlier than expected. Tomorrow AM? Or remote pair tonight even?

**Comment by alanjosephwilliams** [comment]
Tomorrow AM! Whenever you get in works

**Comment by daguar** [comment]
:+1: will touch base in the AM about when I'll likely be heading in, but I'm thinking regular time ~10am ish.

**Comment by daguar** [comment]
@alanjosephwilliams is working on friendly error message finalization after we paired briefly this AM

**Comment by daguar** [comment]
w00t done :shipit:
