### ISSUE TITLE
Upload progress bar too small and checkmark too big on mobile

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#498]
- [ ] Progress bar mobile-responsive
- [ ] Success checkmark super big on mobile

![screen shot 2015-04-20 at 4 15 25 pm](https://cloud.githubusercontent.com/assets/2533112/7242573/7c494630-e778-11e4-99dd-3b1f4b9ec17d.png)

Let's make it big and useful.

This will also be related to #497 .

**Comment by alanjosephwilliams** [comment]
:+1:

**Comment by daguar** [comment]
(talking with AJW) — the checkmark on mobile is also very big; editing this issue to include this.

**Comment by alanjosephwilliams** [comment]
The scope of this work is somewhat to be determined—the current implementation uses tables, and we'll have to test the ability for the current table structure to meet our needs regarding responsive layouts.

**Comment by daguar** [comment]
Closed by #505
