### ISSUE TITLE
Lit review on recidivism

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#50]
Would be great to get a review of the evidence base on recidivism and to what extent access to public benefits can reduce it.
- http://journals.psychiatryonline.org/article.aspx?articleid=98119
- http://www.antoniocasella.eu/archipsy/Morrissey_2006.pdf
- http://alliance1.metapress.com/content/x532221860826128/
- http://journals.psychiatryonline.org/article.aspx?articleid=98119
- http://www.governing.com/news/headlines/How-Medicaid-Expansion-Lowers-Prison-Costs-Recidivism.html
- https://www.ncjrs.gov/pdffiles1/nij/grants/214169.pdf

**Comment by alanjosephwilliams** [comment]
let's move this kind of research task out of Clean repo and into the Health wiki—though obviously our interest in recidivism has waned since early summer.

**Comment by lippytak** [comment]
@jmadans see some primary resources above if you're still interested in this.
