### ISSUE TITLE
Investigate the potential problem Xiao reported with doc receipt

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clean#541]

**Comment by daguar** [comment]
Verifications are at the end of the PDF sent to HSA, so if anything's up it's on HSA's side. Xiao reported that an EW said there's a backlog right now so my guess is that's it, possibly even more likely since these are Chinese-language documents.

**Comment by lippytak** [comment]
@daguar thanks for digging into this. Anything else we need to do here? Want me to research the specific case with Carissa?

**Comment by daguar** [comment]
@lippytak That'd be great! Can you email her the names of the clients and ask her to look into them, CCing me?

All the clients applied on the same day (May 5) and none of them have received interviews yet, so looking into 1 case should probably tell us what's going on with all of them.

**Comment by lippytak** [comment]
Confirmed this is just cases waiting in the regular queue. Nothing to see here, folks.
