### ISSUE TITLE
Improve image upload for low bandwidth connections

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#63]
CalFresh usually requires 4 verification docs. Users should be able to submit/upload these docs via a low bandwidth connection (at least MiFi for v3). This was an issue in v2. We probably have to do some client-side img compression before upload. Some relevant links:
- http://stackoverflow.com/questions/14672746/how-to-compress-an-image-via-javascript-in-the-browser
- http://stackoverflow.com/questions/961913/image-resize-before-upload

**Comment by alanjosephwilliams** [comment]
Definitely closing this.
