### ISSUE TITLE
Bug: Signature field doesn’t work on Windows RT

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/clean#98]
The signature field doesn’t work on Windows RT tablets. I doubt we want to fix this but wanted to document nonetheless.

**Comment by alanjosephwilliams** [comment]
Looks like this one should have been closed with #97

**Comment by lippytak** [comment]
You sure? I don't think we've ever successfully tested the sig field on a Windows RT.

**Comment by alanjosephwilliams** [comment]
Nope. Just added to #248

**Comment by lippytak** [comment]
Possible windows RT fix documented here: brinley/jSignature#29

Also worth testing using the official demo to see if our code may be causing the problem: http://willowsystems.github.io/jSignature/#/demo/

**Comment by alanjosephwilliams** [comment]
@lippytak big ups to finding the fix. It's working on the Food Bank tablets ( IE10 / Windows RT) on clean-dev and will be addressed in #354

**Comment by lippytak** [comment]
OMG DID THIS REALLY JUST HAPPEN? Please take a video and send it to me.

**Comment by daguar** [comment]
Thumbs up, way up — let's maybe respond to the email Liliana sent,
informing of the "all new" Clean with working signature for them? (and new
fresh style)



On Tue, Feb 17, 2015 at 6:22 PM, Jake Solomon <notifications@github.com>
wrote:

> OMG DID THIS REALLY JUST HAPPEN? Please take a video and send it to me.
>
> On Tue, Feb 17, 2015 at 6:21 PM, Alan Joseph Williams <
> notifications@github.com> wrote:
>
> > @lippytak <https://github.com/lippytak> big ups to finding the fix. It's
> > working on the Food Bank tablets ( IE10 / Windows RT) on clean-dev and
> will
> > be addressed in #354 <https://github.com/codeforamerica/clean/pull/354>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/codeforamerica/clean/issues/98#issuecomment-74799346
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/issues/98#issuecomment-74799436>.
>



-- 
Dave Guarino
Engineer, Health
(2013 Fellowship alumnus)
Code for America <http://www.codeforamerica.org/>
dave@codeforamerica.org
LinkedIn <http://www.linkedin.com/in/daveguarino/> | GitHub
<https://github.com/daguar/>
